version: '3.8'

volumes:
  pg_data:
  pg_admin:
  static_value:
  media_value:

networks:
  postgres:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:15.4-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ../backend/spanish_with_anna/.env
    networks:
      - postgres
    restart: on-failure

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: ../backend/spanish_with_anna/.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_DISABLE_POSTFIX: 'True'
    volumes:
       - pg_admin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: on-failure

  backend:
    container_name: backend
    build:
      context: ../backend/spanish_with_anna
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    networks:
      - postgres
    depends_on:
      - postgres
    env_file:
      - ../backend/spanish_with_anna/.env 

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes: 
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
    networks:
      - postgres

  nginx:
    container_name: nginx
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ../frontend/:/app/result_build/
    networks:
      - postgres
    depends_on:
      - backend
