# Generated by Django 4.2 on 2023-07-05 13:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Za-яА-ЯёЁ -_]+$')], verbose_name='Имя пользователя')),
                ('email', models.EmailField(error_messages={'unique': 'Пользователь c указанным e-mail уже существует.'}, max_length=254, unique=True, verbose_name='Адрес e-mail')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'Пользователь c указанным номеромтелефона уже существует.'}, max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('student', 'Студент'), ('admin', 'Администратор')], default='user', max_length=15, verbose_name='Роль пользователя')),
                ('language_level', models.CharField(choices=[('A0', 'Нулевой'), ('A1', 'Начальный'), ('A2', 'Базовый'), ('B1', 'Средний'), ('B2', 'Выше среднего'), ('C1', 'Продвинутый'), ('C2', 'Владение в совершенстве')], default='A0', max_length=2, verbose_name='Уровень владения языком')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус пользователя (активный/неактивный)')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Доступ к админке Django (да/нет)')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперпользователь (да/нет)')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('is_email_confirmed', models.BooleanField(default=False, verbose_name='Статус подтверждения email')),
                ('courses', models.ManyToManyField(related_name='courses', to='courses.course', verbose_name='Курсы пользователя')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯёЁ -_]+$')], verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон')),
                ('preferred_communication', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email')], default='phone', max_length=15, verbose_name='Предпочитаемый способ коммуникации')),
                ('message', models.TextField(max_length=1024, verbose_name='Сообщение')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_agree', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Обращение обратной связи закрыто')),
                ('is_double', models.BooleanField(default=False, verbose_name='Дубль обращения обратной связи')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к обратной связи')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ('-time_create',),
            },
        ),
    ]
