import Head from 'next/head';
import { poppins } from '@/utils/fonts';
import styles from '@/styles/pages/Home.module.scss';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${poppins.className}`}>
        <p>Here will be something soon</p>
      </main>
    </>
  );
}
