import Head from 'next/head';
import { poppins } from '@/assets/fonts/fonts';
import Footer from '@/components/Footer/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${poppins.className}`}>
        <p>Here will be something soon</p>
      </main>
      <Footer />
    </>
  );
}
